<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Megha-PC" name="APITests" tests="3" failures="1" timestamp="30 Dec 2017 05:23:09 GMT" time="11.404" errors="0">
  <testcase name="Validate_Response_Time" time="1.379" classname="APITest.RestTest"/>
  <testcase name="Validate_Image_URL" time="9.66" classname="APITest.RestTest"/>
  <testcase name="Validate_Component_AnalyticsData" time="0.325" classname="APITest.RestTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
Verified Component:2 does not contain analytics_name, Verified Component:4 does not contain analytics_name">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Verified Component:2 does not contain analytics_name, Verified Component:4 does not contain analytics_name
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:38)
	at APITest.RestService.getAnalyticsData(RestService.java:238)
	at APITest.RestTest.Validate_Component_AnalyticsData(RestTest.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Component_AnalyticsData -->
</testsuite> <!-- APITests -->
